github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Krazo]
description: [Eclipse Krazo is an implementation of action-based MVC specified by Jakarta MVC.]

latestVersion: '2.0.1'

links:
  source: https://github.com/eclipse-ee4j/krazo
  docs: https://eclipse-ee4j.github.io/krazo.github.io/documentation/latest/index.html
  #javadocs: https://eclipse-ee4j.github.io/krazo.github.io/apidocs/latest/krazo/index.html
  download: https://eclipse-ee4j.github.io/krazo/downloads/index.html
  mailinglist: https://accounts.eclipse.org/mailing-list/krazo-dev
  hide_issuetracker: true
  #faq: FAQ
