github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Krazo]
description: [Eclipse Krazo is a REST framework that provides a JAX-RS (JSR-370) implementation and more]

latestVersion: '1.1.0'

links:
  source: https://github.com/eclipse-ee4j/krazo
  #docs: https://eclipse-ee4j.github.io/krazo.github.io/documentation/latest/index.html
  #javadocs: https://eclipse-ee4j.github.io/krazo.github.io/apidocs/latest/krazo/index.html
  download: https://eclipse-ee4j.github.io/krazo/download.html
  mailinglist: https://accounts.eclipse.org/mailing-list/krazo-dev
  hide_issuetracker: true
  #faq: FAQ
