////

    Copyright (c) 2019-2022 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////

== Configuration

This section describes how you can configure your MVC application by overwriting properties inside the Jakarta REST Application class.
For example, you can overwrite an exemplary property `foo` inside the Application like this:

[source,java]
....
public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put("foo", "bar");

        return props;
    }
}
....

=== CSRF

For the usage of CSRF, the MVC API and Krazo provide different properties to customize its behavior.

==== Csrf.CSRF_PROTECTION (jakarta.mvc.security.CsrfProtection)

By default, the CSRF protection for MVC resources is set to `Csrf.CsrfOptions#EXPLICIT`, which means, that you're required to set the `@CsrfProtected` annotation over a Controller method annotated with `@POST`, `@PUT`, `@PATCH` or `@DELETE`.
In case you want to use CSRF protection in all methods annotated with one of these HTTP verbs, you can set the property `jakarta.mvc.security.CsrfProtection` to `CsrfOptions#IMPLICIT`.

[source,java]
....
import jakarta.mvc.security.Csrf;
import jakarta.mvc.security.Csrf.CsrfOptions;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Csrf.CSRF_PROTECTION, CsrfOptions.IMPLICIT);

        return props;
    }
}
....

Although, you might want to disable CSRF protection completely for you application.
Therefore exists the `CsrfOptions#OFF` value, which can be set like the
`CsrfOptions#IMPLICIT` value in the example above.

==== Csrf.CSRF_HEADER_NAME (jakarta.mvc.security.CsrfHeaderName)

Sometimes you may want to set a custom value for the header transporting the CSRF token.
For this task you can use the property `jakarta.mvc.security.CsrfHeaderName` or its constant `Csrf.CSRF_PROTECTION`.
Overwriting this property will change the default name of the HTTP header from `X-CSRF-TOKEN` to any valid HTTP header name.
The property can be changed like this:

[source,java]
....
import jakarta.mvc.security.Csrf;
import jakarta.mvc.security.Csrf.CsrfOptions;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Csrf.CSRF_HEADER_NAME, "X-CUSTOM-CSRF-HEADER");

        return props;
    }
}
....

==== Properties.CSRF_TOKEN_STRATEGY (org.eclipse.krazo.csrfTokenStrategy)

To generate CSRF tokens, Krazo provides two mechanisms by default: a cookie-based and a session-based algorithm, where the session-based is set as default.
In case you want to change the strategy or even want to use some custom one, you can change the used strategy with the `org.eclipse.krazo.csrfTokenStrategy` property.
For example, you can switch to the cookie-based token strategy by using this setting:

[source,java]
....
import org.eclipse.krazo.Properties;
import org.eclipse.krazo.security.CsrfTokenStrategy;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Properties.CSRF_TOKEN_STRATEGY, CookieCsrfTokenStrategy.Builder.build());

        return props;
    }
}
....

The `org.eclipse.krazo.security.CookieCsrfTokenStrategy` can be customized via its `Builder`, but that isn't in the scope of this documentation.
Please have a look into the JavaDoc for this.

=== Views

Eclipse Krazo provides some configuration properties, where someone can customize the behavior of the view handling.
These configurations will be described in the following sections.

==== Properties.REDIRECT_SCOPE_COOKIES (org.eclipse.krazo.redirectScopeCookies)

By default, Krazo uses a URL re-write mechanism to store the information about `@RedirectScoped` beans.
In case someone doesn't want this behavior, Krazo also supports a cookie-based strategy for this task. To enable this feature, the property `org.eclipse.krazo.redirectScopeCookies` needs to be overwritten inside the Jakarta REST Application class:

[source,java]
....
import org.eclipse.krazo.Properties;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Properties.REDIRECT_SCOPE_COOKIES, true);

        return props;
    }
}
....

==== Properties.REDIRECT_SCOPE_COOKIE_NAME (org.eclipse.krazo.redirectScopeCookieName)

When you use the _cookie based_ approach to handle the redirect scope, the default cookie name is `org.eclipse.krazo.redirect.Cookie`. In case this name doesn't match your requirements, there is a property called `org.eclipse.krazo.redirectScopeCookieName` to overwrite it. The example shows how this can be achieved.

[source,java]
....
import org.eclipse.krazo.Properties;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Properties.REDIRECT_SCOPE_COOKIE_NAME, "my_redirect_cookie");

        return props;
    }
}
....

This example would let Krazo create a Cookie called `my_redirect_cookie` containing the redirect scope token.

==== Properties.REDIRECT_SCOPE_QUERY_PARAM_NAME (org.eclipse.krazo.redirectScopeQueryParamName)

On the other hand, when you use the _query param_ based approach, which is the default setting, you can
change the query param's name from `org.eclipse.krazo.redirect.param.ScopeId` to something more concise by using
the property `org.eclipse.krazo.redirectScopeQueryParamName`. The example shows to how this can be done inside the
Jakarta REST application.

[source,java]
....
import org.eclipse.krazo.Properties;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Properties.REDIRECT_SCOPE_QUERY_PARAM_NAME, "redirect_token");

        return props;
    }
}
....

Now the query param would be something like `/foo?redirect_token=[some UUID]` instead of `/foo?org.eclipse.krazo.redirect.param.ScopeId=[some UUID]`.

==== Properties.DEFAULT_VIEW_FILE_EXTENSION (org.eclipse.krazo.defaultViewFileExtension)

While developing a completely new MVC application, someone normally just uses one template engine for all of its views.
This means, that every view file ends with the same extension and this leads to less readable code.
To set this extension as a default for all view files, Krazo provides the property
`org.eclipse.krazo.defaultViewFileExtension`, which takes a string containing the name of the file extension:

[source,java]
....
import org.eclipse.krazo.Properties;

public class MyApplication extends Application {

    @Override
    public Map<String, Object> getProperties() {
        final Map<String, Object> props = new HashSet<>();

        props.put(Properties.DEFAULT_VIEW_FILE_EXTENSION, "jsp");

        return props;
    }
}
....

In this example, Krazo will assume that every view is a JSP file.
So in case you return the view `edit` from your Controller, Krazo will search for a file `edit.jsp`.
