////

    Copyright (c) 2019-2022 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////
== Introduction

Eclipse Krazo is an implementation of action-based MVC specified by Jakarta MVC.
It builds on top of Jakarta RESTful Web Services (former JAX-RS; abbreviated with Jakarta REST inside this documentation)  and currently contains support for RESTEasy and Jersey
with a well-defined SPI for other implementations.

This is the user guide for Eclipse Krazo {krazo-version}. We are trying to keep it up to date with the current features. Please note, that this guide assumes that the examples are, if not specified otherwise, targeting a Jakarta EE 10 environment.
