////

    Copyright (c) 2019-2022 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////
== Quickstart

This section describes how to set up Eclipse Krazo.

=== Basic setup

The required steps to set up Eclipse Krazo depends on your environment. The easiest way is to
use a Jakarta EE environment, because in this case the server already provides all the
prerequisites.

==== Jakarta EE

The easiest way getting started with Eclipse Krazo is to generate a Jakarta EE project with our
archetype. This archetype generates a simple project including the Jakarta EE Web Profile and the selected,
server-specific Krazo implementation.

This archetype comes with the following setups:

- Java EE 8 / Jakarta EE 8: MVC 1.0, Krazo 1.1.0
- Jakarta EE 9: MVC 2.0, Krazo 2.0.x
- Jakarta EE 10: MVC 2.1, Krazo 3.0.0

Please note that since Krazo 3.0.0 the name of the archetype changed. Before this release, all archetypes contained the target Jakarta EE release in their names which led to confusing versioning. Since Krazo 3.0.0 the archetype targets the same Jakarta EE release than Krazo and the corresponding Jakarta MVC API.

===== How to use the archetype

The usage of the archetype is really easy. Depending on your application server, just run one of these commands in your command line.

====== Glassfish / Payara (Jersey) (since Krazo 3.0.0)

[source, subs="attributes"]
----
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee-archetype \
-DarchetypeVersion=KRAZO VERSION  \
-DgroupId=YOUR GROUP ID\
-DartifactId=YOUR ARTIFACT ID
----

====== Wildfly (RESTEasy) / OpenLiberty >= 21.x (since Krazo 3.0.0)

[source, subs="attributes"]
----
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee-archetype \
-DarchetypeVersion=KRAZO VERSION \
-DgroupId=YOUR GROUP ID \
-DartifactId=YOUR ARTIFACT ID \
-DkrazoImpl=resteasy
----

====== Glassfish / Payara (Jersey) (before Krazo 3.0.0)

[source, subs="attributes"]
----
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee[8|9]-archetype \
-DarchetypeVersion=[1.1.0 | 2.0.x]  \
-DgroupId=YOUR GROUP ID\
-DartifactId=YOUR ARTIFACT ID
----

====== Wildfly (RESTEasy) / OpenLiberty >= 21.x (before Krazo 3.0.0)

[source, subs="attributes"]
----
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee[8|9]-archetype \
-DarchetypeVersion=[1.1.0 | 2.0.x] \
-DgroupId=YOUR GROUP ID \
-DartifactId=YOUR ARTIFACT ID \
-DkrazoImpl=resteasy
----

====== TomEE / OpenLiberty (CXF)
Krazo won't support CXF anymore. As OpenLiberty is going to switch to RESTEasy until it supports Jakarta REST Web Services 3.0, this change is only relevant for TomEE in general and older versions of OpenLiberty.

To use Krazo on those servers anyway, you can add Jersey or RESTEasy as a compile time dependency to your artifact/

====== Glassfish/Payara

Glassfish comes with Jersey as its Jakarta REST implementation. Please add the following dependencies to your
application:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>jakarta.mvc</groupId>
        <artifactId>jakarta.mvc-api</artifactId>
        <version>{{versions.spec.latest}}</version>
    </dependency>

    <dependency>
        <groupId>org.eclipse.krazo</groupId>
        <artifactId>krazo-jersey</artifactId>
        <version>{{versions.krazo.latest}}</version>
    </dependency>

    <!-- other dependencies ... -->
</dependencies>
----

====== Wildfly, JBoss EAP and OpenLiberty >= 21.x

Wildfly is using RESTEasy for Jakarta REST. So you need the Eclipse Krazo RESTEasy integration module:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>jakarta.mvc</groupId>
        <artifactId>jakarta.mvc-api</artifactId>
        <version>{{versions.spec.latest}}</version>
    </dependency>
    <dependency>
        <groupId>org.eclipse.krazo</groupId>
        <artifactId>krazo-resteasy</artifactId>
        <version>{{versions.krazo.latest}}</version>
    </dependency>

    <!-- other dependencies ... -->
</dependencies>
----

====== Thorntail

Since version 2.7.0, Thorntail provides a stable fraction for MVC with Krazo. For older versions of Thorntail you can use the Jakarta REST fraction and add
the same dependencies as required for WildFly.

Please note, that Thorntail link:https://thorntail.io/posts/the-end-of-an-era/[reached end of life] and therefore the MVC fraction won't receive updates anymore.

==== Servlet Containers

The simplest way to get started with MVC is to deploy your app to a JavaEE 8 application server.
In this setup the application server will provide Jakarta REST, CDI and Bean Validation implementations
for you. However, there is a large number of users who prefer to run their applications on plain Servlet containers
like Apache Tomcat and Jetty. In this setup you will have to provide Jakarta REST, CDI and Bean Validations
yourself.

The following steps will show you how to run Eclipse Krazo on Apache Tomcat using Weld, Jersey and Hibernate Validator (used by Jersey Bean Validation).

=== Required dependencies

The following `pom.xml` example shows the dependency configuration for your application. Please use the corresponding versions according to the Jakarta EE platform you target.

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <scope>compile</scope>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-server</artifactId>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-common</artifactId>
        <scope>compile</scope>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.inject</groupId>
        <artifactId>jersey-hk2</artifactId>
    </dependency>

    <dependency>
        <groupId>jakarta.validation</groupId>
        <artifactId>jakarta.validation-api</artifactId>
        <scope>compile</scope>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.ext</groupId>
        <artifactId>jersey-bean-validation</artifactId>
    </dependency>

    <dependency>
        <groupId>jakarta.enterprise</groupId>
        <artifactId>jakarta.enterprise.cdi-api</artifactId>
        <scope>compile</scope>
    </dependency>

    <dependency>
        <groupId>org.jboss.weld.servlet</groupId>
        <artifactId>weld-servlet-core</artifactId>
        <scope>compile</scope>
    </dependency>

    <dependency>
        <groupId>org.glassfish.jersey.ext.cdi</groupId>
        <artifactId>jersey-cdi1x-servlet</artifactId>
    </dependency>

    <dependency>
        <groupId>org.eclipse.krazo</groupId>
        <artifactId>krazo-jersey</artifactId>
        <version>${krazo.version}</version>
    </dependency>
</dependencies>
----

=== Configuration files

Make sure to add an empty `beans.xml` file in your `/src/main/webapp/WEB-INF` folder:

[source,xml]
----
<?xml version="1.0"?>
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd"
       version="4.0">

</beans>
----

Please note, that the default `bean-discovery-mode` changed to `annotated` in CDI 4.0. In case you want to use the old behavior, set the `bean-discovery-mode` to `all` in the `beans.xml`

The next file to create is called `web.xml` and should be placed in the `src/main/webapp/WEB-INF` directory:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd"
         version="5.0" metadata-complete="true">

</web-app>
----

The attribute `metadata-complete` isn't madantory, but link:https://issues.jboss.org/browse/RESTEASY-2289[helps to prevent Krazo starting twice on RESTEasy]

==== Mixed configuration with Application#getClasses and Jakarta REST auto discovery

As an alternative to the resource auto-discovery of Jakarta REST, someone can use `Application#getClasses` to configure
endpoints or other providers. Unfortunately, this disables the auto-discovery of Jakarta REST completely, which leads to
not loaded Krazo classes and errors or misbehavior during runtime. In case you want to use the manual approach together
with Eclipse Krazo, you have to consider following configurations.

===== RESTEasy and Jersey

You don't need additional configuration, as Krazo is auto-loaded by implementation-specific SPIs.

=== Creating you first controller

The following steps will show you how to create your first Controller using Eclipse Krazo. It assumes, that you've set up a project like we described before.

The first step is to create an Application class, which serves as root resource for our Controllers. The Application class extends from Jakarta REST `Application` and provides
the base path of our application.

[source,java]
....
import jakarta.ws.rs.Application;
import jakarta.ws.rs.core.Application;

@Application("mvc")
public class MyApplication extends Application {

}
....

Please note that, according to the MVC specification, it is not recommended to use an empty application path, as this can lead to problems during request handling when using servlets and MVC resources in parallel or whenyou try to access a stylesheet served by the servlet container via `src/main/webapp`.

After we created the Application class, we need to add our Controller. Therefore, you need to add a simple Jakarta REST resource and decorate it with the `jakarta.mvc.Controller` annotation.


[source,java]
....
@Path("hello")
public class HelloController {

    @GET
    @Controller
    public String hello() {
        return "hello.jsp";
    }
}
....

Now you should see the content of `hello.jsp` when you access the URI `/mvc/hello` in your browser.
