////

    Copyright (c) 2019 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////
== Quickstart

This section describes how to set up Eclipse Krazo.

=== Basic setup

The required steps to set up Eclipse Krazo depends on your environment. The easiest way is to
use a Java EE 8 / Jakarta EE environment, because in this case the server already provides all the
prerequisites.

==== Java EE 8 / Jakarta EE

The easiest way getting started with Eclipse Krazo is to generate a Jakarta EE project with our
archetype. This archetype generates a simple project including the Jakarta EE Web Profile and the selected,
server-specific Krazo implementation.


===== How to use the archetype

The usage of the archetype is really easy. Depending on your application server, just run one of these commands in your command line.

====== Glassfish / Payara (Jersey)

[source, subs="attributes"]
....
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee8-archetype \
-DarchetypeVersion={krazo-version}  \
-DgroupId=YOUR GROUP ID\
-DartifactId=YOUR ARTIFACT ID
....

====== Wildfly (RESTEasy)

[source, subs="attributes"]
....
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=krazo-jakartaee8-archetype \
-DarchetypeVersion={krazo-version} \
-DgroupId=YOUR GROUP ID \
-DartifactId=YOUR ARTIFACT ID \
-DkrazoImpl=resteasy
....

====== TomEE / OpenLiberty (CXF)
Krazo won't support CXF anymore. As OpenLiberty is going to switch to RESTEasy until it supports Jakarta REST Web Services 3.0, this change is only relevant for TomEE in general and older versions of OpenLiberty.

To use Krazo on those servers anyway, you can add e.g. RESTEasy as a compile time dependency to your artifact:

[source,xml]
----
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-resteasy</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-cdi</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-servlet-initializer</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-validator-provider-11</artifactId>
    <version>3.6.1.Final</version>
</dependency>
----


====== Glassfish/Payara

Glassfish comes with Jersey as its JAX-RS implementation. Please add the following dependencies to your
application:

[source,xml]
----
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-jersey</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
----

====== Wildfly and JBoss EAP

Wildfly is using RESTEasy for JAX-RS. So you need the Eclipse Krazo RESTEasy integration module:

[source,xml]
----
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-resteasy</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
----

====== Apache TomEE

To use Krazo on TomEE, you can add RESTEasy as a compile time dependency, as CXF isn't supported anymore by Krazo.

[source,xml]
----
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-resteasy</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-cdi</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-servlet-initializer</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-validator-provider-11</artifactId>
    <version>3.6.1.Final</version>
</dependency>
----

====== Thorntail

Since version 2.7.0, Thorntail provides a stable fraction for MVC with Krazo. For older versions of Thorntail you can use the JAX-RS fraction and add
the same dependencies as required for WildFly:

[source,xml]
----
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>jaxrs</artifactId>
</dependency>
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-resteasy</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
----

using fraction :

[source,xml]
----
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>mvc</artifactId>
</dependency>
----

Please note, that Thorntail link:https://thorntail.io/posts/the-end-of-an-era/[reached end of life] and therefore the MVC fraction will only receive critical bug fixes.

==== Servlet Containers

The simplest way to get started with MVC is to deploy your app to a JavaEE 8 application server.
In this setup the application server will provide JAX-RS, CDI and Bean Validation implementations
for you. However, there is a large number of users who prefer to run their applications on plain Servlet containers
like Apache Tomcat and Jetty. In this setup you will have to provide JAX-RS, CDI and Bean Validations
yourself.

The following steps will show you how to run Eclipse Krazo on Apache Tomcat using Weld, RESTEasy and Hibernate Validator.

=== Required dependencies

The following `pom.xml` example shows the dependency configuration for your application:

[source,xml]
----
<!-- Get the API JARs for Jakarta EE 8 -->
<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-web-api</artifactId>
    <version>8.0.0</version>
</dependency>

<!-- Weld  -->
<dependency>
    <groupId>org.jboss.weld.servlet</groupId>
    <artifactId>weld-servlet-core</artifactId>
    <version>3.0.5.Final</version>
</dependency>

<!-- RESTEasy -->
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-cdi</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-servlet-initializer</artifactId>
    <version>3.6.1.Final</version>
</dependency>

<!-- Bean Validation -->
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-validator-provider-11</artifactId>
    <version>3.6.1.Final</version>
</dependency>

<!-- MVC + Eclipse Krazo for RESTEasy-->
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-resteasy</artifactId>
    <version>{{versions.krazo.latest}}</version>
</dependency>
----

=== Configuration files

Make sure to add an empty `beans.xml` file in your `/src/main/webapp/WEB-INF` folder:

[source,xml]
----
<?xml version="1.0"?>
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_3_0.xsd"
       version="3.0" bean-discovery-mode="all">

</beans>
----

Please also add a file called `context.xml` to `src/main/resources/META-INF`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Context>

   <Resource name="BeanManager" auth="Container"
             type="jakarta.enterprise.inject.spi.BeanManager"
             factory="org.jboss.weld.resources.ManagerObjectFactory"/>

</Context>
----

This file `context.xml` is essential for the operation of the CDI in Tomcat as described in the
link:http://docs.jboss.org/weld/reference/latest/en-US/html_single/#tomcat[Weld documentation].

The file to create is called `web.xml` and should be placed in the `src/main/webapp/WEB-INF` directory:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_4_0.xsd"
         version="4.0" metadata-complete="true">

  <listener>
    <listener-class>org.jboss.weld.environment.servlet.Listener</listener-class>
  </listener>

  <resource-env-ref>
    <resource-env-ref-name>BeanManager</resource-env-ref-name>
    <resource-env-ref-type>jakarta.enterprise.inject.spi.BeanManager</resource-env-ref-type>
  </resource-env-ref>

  <!-- http://docs.jboss.org/resteasy/docs/3.6.1.Final/userguide/html_single/index.html#d4e143 -->
  <context-param>
    <param-name>resteasy.injector.factory</param-name>
    <param-value>org.jboss.resteasy.cdi.CdiInjectorFactory</param-value>
  </context-param>

</web-app>
----

The attribute `metadata-complete` isn't madantory, but link:https://issues.jboss.org/browse/RESTEASY-2289[helps to prevent Krazo starting twice on RESTEasy]

==== Mixed configuration with Application#getClasses and JAX-RS auto discovery

As an alternative to the resource auto-discovery of JAX-RS, someone can use `Application#getClasses` to configure
endpoints or other providers. Unfortunately, this disables the auto-discovery of JAX-RS completely, which leads to
not loaded Krazo classes and errors or misbehavior during runtime. In case you want to use the manual approach together
with Eclipse Krazo, you have to consider following configurations.

===== RESTEasy and Jersey

You don't need additional configuration, as Krazo is auto-loaded by implementation-specific SPIs.

=== Creating you first controller

The following steps will show you how to create your first Controller using Eclipse Krazo. It assumes, that you've set up a project like we described before.

The first step is to create an Application class, which serves as root resource for our Controllers. The Application class extends from JAX-RS `Application` and provides
the base path of our application.

[source,java]
....
import jakarta.ws.rs.Application;
import jakarta.ws.rs.core.Application;

@Application("mvc")
public class MyApplication extends Application {

}
....

Please note that, according to the MVC specification, it is not recommended to use an empty application path, as this can lead to problems during request handling.

After we created the Application class, we need to add our Controller. Therefore you need to add a simple JAX-RS resource and decorate it with the
`jakarta.mvc.Controller` interface.


[source,java]
....
@Path("hello")
public class HelloController {

    @GET
    @Controller
    public String hello() {
        return "hello.jsp";
    }
}
....

Now you should see the content of `hello.jsp` when you access the URI `/mvc/hello` in your browser.
