////

    Copyright (c) 2019 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////
== Quickstart

This section describes how to set up Eclipse Krazo.

=== Basic setup

The required steps to set up Eclipse Krazo depends on your environment. The easiest way is to
use a Java EE 8 / Jakarta EE environment, because in this case the server already provides all the
prerequisites.

==== Java EE 8 / Jakarta EE

The easiest way getting started with Eclipse Krazo is to generate a Jakarta EE project with our
archetype. This archetype generates a simple project including the Jakarta EE Web Profile and the selected,
server-specific Krazo implementation.


===== How to use the archetype

The usage of the archetype is really easy. Depending on your application server, just run one of these commands in your command line.

====== Glassfish / Payara (Jersey)

[source, subs="attributes"]
....
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=jakartaee8-archetype \
-DarchetypeVersion={krazo-version}  \
-DgroupId=YOUR GROUP ID\
-DartifactId=YOUR ARTIFACT ID
....

====== Wildfly (RESTEasy)

[source, subs="attributes"]
....
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=jakartaee8-archetype \
-DarchetypeVersion={krazo-version} \
-DgroupId=YOUR GROUP ID \
-DartifactId=YOUR ARTIFACT ID \
-DkrazoImpl=resteasy
....

====== TomEE / OpenLiberty (CXF)

[source, subs="attributes"]
....
mvn archetype:generate \
-DarchetypeGroupId=org.eclipse.krazo \
-DarchetypeArtifactId=jakartaee8-archetype \
-DarchetypeVersion={krazo-version} \
-DgroupId=YOUR GROUP ID \
-DartifactId=YOUR ARTIFACT ID \
-DkrazoImpl=cxf
....

==== Servlet Containers

TODO: Migrate relevant parts from the website

=== Creating you first controller

TODO: Create Application class and create the first controller

