////

    Copyright (c) 2019 Eclipse Krazo committers and contributors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    SPDX-License-Identifier: Apache-2.0

////
== Quickstart

This section describes how to set up Eclipse Krazo.

=== Basic setup

The required steps to set up Eclipse Krazo depends on your environment. The easiest way is to
use a Java EE 8 / Jakarta EE environment, because in this case the server already provides all the
prerequisites.

==== Java EE 8 / Jakarta EE

TODO: Migrate relevant parts from the website

==== Servlet Containers

TODO: Migrate relevant parts from the website

==== Mixed configuration with Application#getClasses and JAX-RS auto discovery

As an alternative to the resource auto-discovery of JAX-RS, someone can use `Application#getClasses` to configure
endpoints or other providers. Unfortunately, this disables the auto-discovery of JAX-RS completely, which leads to
not loaded Krazo classes and errors or misbehavior during runtime. In case you want to use the manual approach together
with Eclipse Krazo, you have to consider following configurations.

===== RESTEasy and Jersey

You don't need additional configuration, as Krazo is auto-loaded by implementation-specific SPIs.

===== CXF

As CXF doesn't provide any SPI to enforce the initialization of Eclipse Krazo, you need to configure all necessary
providers manually in `Application#getClasses`. Please have a look into the snippet below, which shows an example
implementation of `Application#getClasses`.

....
public class MyApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<>();

        ...

        // Add Krazo features
        classes.add(ViewResponseFilter.class);
        classes.add(ViewableWriter.class);
        classes.add(CsrfValidateFilter.class);
        classes.add(CsrfProtectFilter.class);
        classes.add(CsrfExceptionMapper.class);
        classes.add(PreMatchingRequestFilter.class);
        classes.add(PostMatchingRequestFilter.class);
        classes.add(MvcConverterProvider.class);
        classes.add(HiddenMethodFilter.class);

        return classes;
    }
}
....

=== Creating you first controller

TODO: Create Application class and create the first controller


